before_script:
  - apt-get update
  - apt-get -y install docker.io


build:
  stage: build
  script:
    - docker build ./src/MVS.Template.CSharp.Infrastructure -t ${docker_image_name}:${TAG:-latest}
  tags:
    - linux