language: csharp
mono: none
dist: xenial
dotnet: 3.1
services:
  - docker
script:
  - dotnet build tools/MVS.Scaffolding/MVS.Scaffolding.csproj
  - dotnet pack tools/MVS.Scaffolding -o artifacts --version-suffix dev-1
  - dotnet test ./test/MVS.Template.CSharp.UnitTest/MVS.Template.CSharp.UnitTest.csproj
after_success:
  - test "$TRAVIS_BRANCH" = "master" && sh scripts/deploy_heroku.sh