version: '3.3'

services: 
    
  mvs-template-csharp-api:
    image: ${docker_image_name:-mvs-template-csharp-api}:${TAG:-latest}
    build:
      context: .
      dockerfile: src/MVS.Template.CSharp.Infrastructure/Dockerfile
